### ISSUE TITLE
Display selected plugin readme

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os/ubiquity-os-plugin-installer#15]
Does it make sense to pull the selected plugin's README and display it beside the editor?

This should improve UX as it consolidates plugin install and usage info into one place and should give insight into every config option. The downside is that READMEs must be accurate and up to date.

![image](https://github.com/user-attachments/assets/05df6644-6ac7-43f9-915b-bd5a6fe956a2)

**Comment by rndquu** [comment]
Closing in favor of https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/19
