### ISSUE TITLE
Customization default render

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os/ubiquity-os-plugin-installer#17]
When a plugin is selected from the dropdown right now the defaults based on the schema are imported into the inputs to meet that `one-click-install` approach.

1. Should we load their current config values into the editor if they have that plugin installed?
2. Should we include a button that resets the values to defaults?
3. Should we have an option to copy our official config settings 1:1 for A) per-plugin B) full config copy/paste? Some plugins/settings need to be handled manually for things like `evmPrivateEncrypted`

**Comment by rndquu** [comment]
Closing in favor of https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/19
