### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by rndquu** [ubiquity-os/ubiquity-os-plugin-installer#19]
Depends on https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/13

What should be done:
1. The "select configuration" step should be removed. Always use the "production" config.
2. Show plugin readme on installing a new plugin (original [comment](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/15#issue-2646661367))
3. Show indicator if plugin is already installed (original [comment](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/16#issue-2647181893))
4. Load current config values in the editor (if config is present)
5. Add "Reset to defaults" button which resets plugin options to default values (original [comment](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/17#issue-2647183231))
6. Add github redirect to the same page ([example](https://github.com/ubiquity/work.ubq.fi/blob/5ad2731d99f3c03cdb52fe5f7122e412669ca0bd/src/home/rendering/render-github-login-button.ts#L37))

**Comment by zugdev** [comment]
I'll take this one as soon as #13 is through.

**Comment by Keyrxng** [comment]
> I'll take this one as soon as #13 is through.

It's all good brother I got things under control here, I'm happy to carry on and clear the new tasks prior to merge. I assume you'll be reviewing my PRs which will take up some time and I assume you have more pressing tasks to address anyway like permit rollups etc

**Comment by Keyrxng** [comment]
> The "select configuration" step should be removed. Always use the "production" config.

@rndquu Is this certain? Are we deprecating the dev bot instance or is this just in terms of partners? i.e including a less visible method of selecting the dev config for internal use? I figured this would be used for development too as @gentlementlegen had mentioned building something similar for his own use

**Comment by rndquu** [comment]
> @rndquu Is this certain? Are we deprecating the dev bot instance or is this just in terms of partners?

Yes, https://github.com/ubiquity-os/ubiquity-os-plugin-installer is for partners. Development config can be created manually at any time.

**Comment by rndquu** [comment]
@Keyrxng Notice a new subtask:
```
6. Add github redirect to the same page ([example](https://github.com/ubiquity/work.ubq.fi/blob/5ad2731d99f3c03cdb52fe5f7122e412669ca0bd/src/home/rendering/render-github-login-button.ts#L37))
```

**Comment by rndquu** [comment]
The bot is not responding because of https://github.com/ubiquity-os/ubiquity-os-kernel/issues/195. I'll try to regenerate later.

**Comment by Keyrxng** [comment]
@rndquu $285 for a < 500 char spec (excluding urls) is amazing compared to $300 for implementing it 😂 I need to up my new task game lmao

**Comment by rndquu** [comment]
> @rndquu $285 for a < 500 char spec (excluding urls) is amazing compared to $300 for implementing it 😂 I need to up my new task game lmao

All text conversation incentive parameters should be fine tuned once the project is transformed into an automated DAO.

**Comment by 0x4007** [comment]
I think we need to remove the priority level multiplier on the spec @gentlementlegen

**Comment by gentlementlegen** [comment]
https://github.com/ubiquity-os/.ubiquity-os/commit/e22141cb0682674d30a2e5f57231ca51c1ed1f5b
https://github.com/ubiquity-os-marketplace/.ubiquity-os/commit/b6eca6949ef6d415a2f6ef623faf8a622d0b4937
https://github.com/ubiquity/.ubiquity-os/commit/a3e7b74559639c846d21285c5f69ca98bcefa39d

**Comment by 0x4007** [comment]
As I understand its the priority level thats the problem. Spec should always be a 3x multiplier. Maybe.

**Comment by zugdev** [comment]
> As I understand its the priority level thats the problem. Spec should always be a 3x multiplier. Maybe.

I agree, priority should apply to review and implementation, but spec doesn't fit that well
