### ISSUE TITLE
Setup GitHub Authentication

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os/ubiquity-os-plugin-installer#2]
As per the `readme.md` of this repo, we need to be able to authenticate to write to the config as the user for this tool to work. 

The logic can likely be lifted from https://github.com/ubiquity/work.ubq.fi

**Comment by 0x4007** [comment]
> /start 

@gentlementlegen Can you find out the root cause of why this is so unreliable

**Comment by gentlementlegen** [comment]
@0x4007 The error on this was:
```
Error in event handler Error: No installation found for owner: ubiquity-os-marketplace
```

Which is not related to the command itself, and I believe it should work now.

**Comment by 0x4007** [comment]
I actually can't assign @Keyrxng i think you need to comment here

**Comment by Keyrxng** [comment]
```diff
+ ~ * checking vibes, please wait... * ~ +
```

**Comment by Keyrxng** [comment]
@gentlementlegen could you generate this reward please mate?
