### ISSUE TITLE
Add permit2 approval

### ISSUE THREAD

**Issue by rndquu** [ubiquity-os/ubiquity-os-plugin-installer#21]
Depends on https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/13

If partner selects to add the https://github.com/ubiquity-os-marketplace/text-conversation-rewards plugin then (depending on the config) partner should also be able to set allowances for permit2 contract.

**Comment by 0x4007** [comment]
Are you sure this should be handled in the context of the installer? I understand why you want it but the UIs/tools should be specialized. It might make more sense to have another simple UI for this. Also, soon, we will migrate to "payment permit requests" architecture which means that the key will not be handled by the single plugin.

**Comment by rndquu** [comment]
> Are you sure this should be handled in the context of the installer?

As far as I understand https://github.com/ubiquity-os/ubiquity-os-plugin-installer should look like a plugins markerplace in the end, not an individual installer.

> I understand why you want it but the UIs/tools should be specialized.

For me it's natural to see all plugin install specific installation steps in a single screen without jumping between UI tools. Anyway we could place the "add permit2 approval" UI to a separate repository and put that URL in the https://github.com/ubiquity-os-marketplace/text-conversation-rewards's plugin readme. Since the [plan](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/19) is to show the plugin readme on plugin installation we could put the "add permit2 approval" URL in the plugin's readme so that partner knew what else is required for the plugin to run.

**Comment by 0x4007** [comment]
> As far as I understand https://github.com/ubiquity-os/ubiquity-os-plugin-installer should look like a plugins markerplace in the end, not an individual installer.

Thats correct

**Comment by rndquu** [comment]
Closing in favor of https://github.com/ubiquity/onboard.ubq.fi/issues/29
