### ISSUE TITLE
`manifest.name` mismatch

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os/ubiquity-os-plugin-installer#27]
Manifests need updated so the name matches the intended name which is the name of the repo it lives in.

![image](https://github.com/user-attachments/assets/9f83088a-2e41-492c-9c8c-d296439c7e79)

Any mismatch in `manifest.name` and the plugin repo and we will not be able to install those plugins and the config will look like this:

![image](https://github.com/user-attachments/assets/3c2101f9-2f49-4e6b-9718-9486b507d0e1)

This is because the worker url contains the repo name and we use that to match against `manifest.name`

_relevant [context](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/24#issuecomment-2493899154)_

**Comment by rndquu** [comment]
Can't we treat `owner/repository` URL as a unique plugin key? Anyway updating the `name` property is already mentioned in https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/24.
