### ISSUE TITLE
Create add/remove config logic

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os/ubiquity-os-plugin-installer#3]
1. We need to be able to select which `ubiquibot-config.yml` to edit, so we at minimum need an organization picker after GitHub authentication. 
2. We need to parse the YML file, and target the config based on the plugin's URL/location. Then edit the YML file and push the commit using the user's credentials.

More thoughts on [the readme](https://github.com/Ubiquity-OS/ubiquity-os-plugin-installer?tab=readme-ov-file#add--remove-config).

### LLM 

Without research, the lazy answer is that LLMs can easily solve the problem. We could even consider passing in the most important/relevant files of the plugin so that the LLM can figure out all the default values and other miscellaneous details. 

But it would certainly be preferred to implement this with traditional code. I think with a bit of research it can be pretty straightforward.

**Comment by 0x4007** [comment]
@gentlementlegen  can you fix the double post?

**Comment by gentlementlegen** [comment]
@0x4007 Spec at https://github.com/ubiquity-os-marketplace/command-start-stop/issues/60

**Comment by Apetree100122** [comment]
``` yml
https://pay.ubq.fi/onboarding
       WALLET_PRIVATE_KEY  field with your
        private key ${{GITHUB_PAT }}
         Set  ORG_NAME 
https://github.com/[YOUR_ORGANIZATION_NAME]/ubiquibot-config
```

**Comment by Apetree100122** [comment]
```yml
https://pay.ubq.fi/onboarding
    ${{WALLET_PRIVATE_KEY}}
      ${{GITHUB_PAT }}
  ORG_NAME 
```

Can find configured@ https://github.com/[YOUR_ORGANIZATION_NAME]/ubiquibot-config

**Comment by Keyrxng** [comment]
starting this now and I'll just link the PR again, it'll be building on top of #12.

**Comment by gentlementlegen** [comment]
Funny, I had made a tool for my personal usage a while ago, I didn't remember this task.

**Comment by Keyrxng** [comment]
> Funny, I had made a tool for my personal usage a while ago, I didn't remember this task.

If it's better than my approach pls share and I'll use it here

**Comment by gentlementlegen** [comment]
@Keyrxng It is a very different approach! At first it was just for editing the configuration files in situ. Also I used NextJs and Material which I don't think is welcome haha.

**Comment by gentlementlegen** [comment]
@0x4007 that's one hell of a spec
