### ISSUE TITLE
Migrate repository to ts-template for better setup and consistency

### ISSUE THREAD

**Issue by jordan-ae** [ubiquity-os/ubiquity-os-plugin-installer#5]
Not sure if this repository was intentionally set up without the existing [ts-template](https://github.com/ubiquity/ts-template/), but I think it would make things a lot easier and more uniform if it had been created using that template. The ts-template includes essential tests and workflows that we might need to rewrite here. It also tackles common issues like linting, pre-commit checks, and more.

While we could manually copy the template files into this repo, certain workflows—like the s[ync-template.yml](ubiquity/ts-template/.github/workflows/sync-template.yml) would no longer work as intended.

Since very little has been done here so far, I suggest we recreate the repo using the ts-template and copy the existing changes over.

**Comment by 0x4007** [comment]
I don't wanna complicate this repo unless it's needed. Pieces of the template can be added later but I wouldn't consider it a priority

**Comment by jordan-ae** [comment]
Should I open a pull request setting up TS, es-build and Yarn or should I just implement #2 with the base you set for the project?

**Comment by 0x4007** [comment]
Not yet
