### ISSUE TITLE
Import Kernel Config Parser

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os/ubiquity-os-plugin-installer#7]
We should import the same parser logic that the kernel uses to keep behavior consistent. 

There should also be another render function to write the config reliably as well.

**Comment by rndquu** [comment]
@Keyrxng This issue can be closed as "not planned" because the manifest parsing and editing is already implemented in https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/13, correct?

**Comment by Keyrxng** [comment]
@rndquu Yeah that's right, it's not the same parsing logic the kernel uses, I'm using AJV to validate but otherwise yes it's implemented.
